inherit_from: .rubocop_todo.yml
require: rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: brackets

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 20
  IgnoredMethods:
  - parse_metadata
  - transform
  - visit_span

Metrics/ClassLength:
  CountAsOne:
  - array
  - hash
  - heredoc
  Max: 200

Metrics/CyclomaticComplexity:
  IgnoredMethods:
  - visit_span

Metrics/MethodLength:
  CountAsOne:
  - array
  - hash
  - heredoc
  Max: 30

Style/StringConcatenation:
  Mode: conservative

Layout/DotPosition:
  EnforcedStyle: trailing
