inherit_from: .rubocop_todo.yml
require: rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Enabled: false

Layout/CommentIndentation:
  AllowForAlignment: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 20
  IgnoredMethods:
  - parse_metadata
  - render
  - transform_volume
  - validate_volumes
  - visit_span
  - visit_body
  - write_anthology
  - write_footnote
  - write_volume

Metrics/BlockLength:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountAsOne:
  - array
  - hash
  - heredoc
  Max: 500

Metrics/CyclomaticComplexity:
  IgnoredMethods:
  - visit_span
  - visit_body
  - visit_text

Metrics/MethodLength:
  CountAsOne:
  - array
  - hash
  - heredoc
  Max: 35
  IgnoredMethods:
  - visit_span

Metrics/PerceivedComplexity:
  IgnoredMethods:
  - visit_span

Style/AndOr:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/NegatedIf:
  Enabled: false

Style/Not:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/StringConcatenation:
  Mode: conservative

Style/SymbolArray:
  EnforcedStyle: brackets
